version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/Task-Manager-using-Flask
    environment:
      FLASK_APP: todo_project/run.py
      FLASK_DEBUG: 1
  test:
    build: .
    command: pytest tests/
    volumes:
      - .:/Task-Manager-using-Flask