version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/Task-Manager-using-Flask
    environment:
      FLASK_APP: todo_project/run.py
      FLASK_DEBUG: 1
      
  bandit:
    build: .
    command: bandit -r todo_project/
    volumes:
      - .:/app

  dependency-check:
    image: owasp/dependency-check
    command: --project MyProject --scan /app/todo_project/
    volumes:
      - .:/app

  zap:
    image: owasp/zap2docker-stable
    ports:
      - "8080:8080"
    command: zap.sh -daemon -host 0.0.0.0 -port 8080

  test:
    build: .
    command: pytest tests/
    volumes:
      - .:/Task-Manager-using-Flask